site_name: Curioustools
site_description: Google certified Associate Android Dev
site_author: Ansh Sachdeva(root-ansh) 
site_url: https://root-ansh.github.io/curioustools/ 


copyright: Copyright &copy; 2019 <a href="https://www.linkedin.com/in/anshsachdevaprofessional/">Ansh Sachdeva</a>


theme:
  name: material
  palette:
        primary: 'white'
        accent: 'green'
  
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/root-ansh
    
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/root_ansh
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anshsachdevawork/
   
